// NormEval Dashboard — app.js
// Tab switching, table rendering, search/filter, sort, export logic
// Note: All data comes from trusted pre-computed DATA_* constants in data.js
// (generated by our own Python script from local JSON files, not user input)

// ============================================================
// Init on DOM ready
// ============================================================
document.addEventListener('DOMContentLoaded', function() {
  renderOverviewTab();
  renderPapersTable();
  renderTrialsTable();
  renderGapsTab();
  renderCrossModelTab();
  renderCrossVendorTab();
  setupTabListeners();
  setupSearch();
  setupSort();
  setupExport();

  // Render overview charts on load
  setTimeout(renderOverviewCharts, 100);
});

// Global tab activation for cross-tab links
function activateTab(tabId) {
  var tabLink = document.querySelector('a[href="#' + tabId + '"]');
  if (tabLink) {
    var tab = new bootstrap.Tab(tabLink);
    tab.show();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}

// ============================================================
// Tab Listeners — lazy render charts
// ============================================================
function setupTabListeners() {
  var tabEls = document.querySelectorAll('a[data-bs-toggle="tab"]');
  var rendered = { overview: true };

  tabEls.forEach(function(tab) {
    tab.addEventListener('shown.bs.tab', function(e) {
      var posEl = document.getElementById('tab-position');
      if (posEl) {
        var idx = Array.from(tabEls).indexOf(e.target) + 1;
        posEl.textContent = 'Tab ' + idx + ' of ' + tabEls.length;
      }
      var target = e.target.getAttribute('href');

      if (target === '#tab-features' && !rendered.features) {
        rendered.features = true;
        setTimeout(renderFeatureCharts, 50);
      } else if (target === '#tab-traditions' && !rendered.traditions) {
        rendered.traditions = true;
        setTimeout(renderTraditionCharts, 50);
      } else if (target === '#tab-composite' && !rendered.composite) {
        rendered.composite = true;
        setTimeout(renderCompositeCharts, 50);
      } else if (target === '#tab-trials' && !rendered.trials) {
        rendered.trials = true;
        setTimeout(renderTrialCharts, 50);
      } else if (target === '#tab-data' && !rendered.data) {
        rendered.data = true;
        setTimeout(renderDataCharts, 50);
      } else if (target === '#tab-crossmodel' && !rendered.crossmodel) {
        rendered.crossmodel = true;
        setTimeout(renderCrossModelCharts, 50);
      } else if (target === '#tab-crossvendor' && !rendered.crossvendor) {
        rendered.crossvendor = true;
        setTimeout(renderCrossVendorCharts, 50);
      } else if (target === '#tab-gaps' && !rendered.gaps) {
        rendered.gaps = true;
        setTimeout(renderGapsCharts, 50);
      }

      // Resize all visible charts
      setTimeout(function() {
        Object.values(chartInstances).forEach(function(c) { c.resize(); });
      }, 100);
    });
  });
}

// ============================================================
// Safe DOM helper: creates text node or element from trusted data
// ============================================================
function setText(el, text) {
  el.textContent = text;
}

function createEl(tag, attrs, children) {
  var el = document.createElement(tag);
  if (attrs) {
    Object.keys(attrs).forEach(function(k) {
      if (k === 'style' && typeof attrs[k] === 'object') {
        Object.assign(el.style, attrs[k]);
      } else if (k === 'className') {
        el.className = attrs[k];
      } else {
        el.setAttribute(k, attrs[k]);
      }
    });
  }
  if (children) {
    if (typeof children === 'string') {
      el.textContent = children;
    } else if (Array.isArray(children)) {
      children.forEach(function(c) { if (c) el.appendChild(c); });
    }
  }
  return el;
}

function showChartLoading(containerId) {
  var el = document.getElementById(containerId);
  if (el && !el.querySelector('canvas') && !el.querySelector('.chart-loading')) {
    var loader = createEl('div', { className: 'chart-loading' }, 'Loading chart\u2026');
    el.appendChild(loader);
  }
}

// ============================================================
// Tab 1: Overview
// ============================================================
function renderOverviewTab() {
  var d = DATA_OVERVIEW;

  // KPI Cards
  var kpiContainer = document.getElementById('kpi-cards');
  kpiContainer.textContent = '';
  var v2h = d.v2_highlights || {};
  var kpis = [
    { value: String(d.n_total), label: 'Benchmarks Analyzed', color: 'blue' },
    { value: String(d.n_pass), label: 'Pass Gates (Top 15)', color: 'green' },
    { value: String(d.n_traditions), label: 'Western Traditions', color: 'purple' },
    { value: '26+20', label: 'Features (v1+v2)', color: 'orange' },
    { value: '750+', label: 'Trial Items', color: 'cyan' },
    { value: String(d.n_fail), label: 'Fail Gates', color: 'red' },
  ];

  kpis.forEach(function(k) {
    var col = createEl('div', { className: 'col-6 col-md-4 col-lg-2' });
    var card = createEl('div', { className: 'metric-card' });
    var val = createEl('div', { className: 'metric-value ' + k.color }, k.value);
    var lbl = createEl('div', { className: 'metric-label' }, k.label);
    card.appendChild(val);
    card.appendChild(lbl);
    col.appendChild(card);
    kpiContainer.appendChild(col);
  });

  // v2 Feature Highlights
  var v2Row = document.getElementById('v2-highlights-row');
  if (v2Row && v2h.e1_avg !== undefined) {
    v2Row.textContent = '';
    var v2Cards = [
      { value: String(v2h.e1_avg), label: 'Avg Discriminative Power (E1)', color: 'blue' },
      { value: v2h.a10_single_turn + '/' + v2h.a10_total, label: 'Single-Turn (A10)', color: 'orange' },
      { value: String(v2h.b10_high_risk), label: 'High Contamination (B10)', color: 'red' },
      { value: String(v2h.nw_engaged) + '/37', label: 'Non-Western Traditions (A1+)', color: 'purple' },
    ];
    v2Cards.forEach(function(k) {
      var col = createEl('div', { className: 'col-6 col-md-3' });
      var card = createEl('div', { className: 'metric-card' });
      var val = createEl('div', { className: 'metric-value ' + k.color, style: 'font-size:1.5rem;' }, k.value);
      var lbl = createEl('div', { className: 'metric-label' }, k.label);
      card.appendChild(val);
      card.appendChild(lbl);
      col.appendChild(card);
      v2Row.appendChild(col);
    });
  }

  // Claims
  var claimsContainer = document.getElementById('claims-list');
  claimsContainer.textContent = '';
  d.claims.forEach(function(c) {
    var statusClass = c.status.toLowerCase();
    var card = createEl('div', { className: 'claim-card' });

    var header = createEl('div', { style: 'display:flex;justify-content:space-between;align-items:center;margin-bottom:0.4rem;' });
    var title = createEl('strong', { style: 'font-size:0.85rem;' }, c.id + ': ' + c.title);
    var badge = createEl('span', { className: 'claim-status ' + statusClass }, c.status);
    header.appendChild(title);
    header.appendChild(badge);

    var desc = createEl('p', { style: 'font-size:0.8rem;color:var(--text-secondary);margin-bottom:0.3rem;' }, c.description);
    var detail = createEl('p', { style: 'font-size:0.75rem;color:var(--text-muted);' }, c.detail);

    card.appendChild(header);
    card.appendChild(desc);
    card.appendChild(detail);
    claimsContainer.appendChild(card);
  });
}

// ============================================================
// Tab 2: Papers Table
// ============================================================
var currentPapers = [];
var currentSort = { key: 'rank', dir: 'asc' };

function renderPapersTable() {
  currentPapers = DATA_PAPERS_TABLE.slice();
  populateYearFilter();
  renderPapersRows();
}

function populateYearFilter() {
  var years = {};
  DATA_PAPERS_TABLE.forEach(function(p) { years[p.year] = true; });
  var sel = document.getElementById('filter-year');
  Object.keys(years).sort().forEach(function(y) {
    var opt = createEl('option', { value: y }, y);
    sel.appendChild(opt);
  });
}

function renderPapersRows() {
  var tbody = document.getElementById('papers-tbody');
  tbody.textContent = '';

  currentPapers.forEach(function(p) {
    // Main data row
    var tr = createEl('tr', { className: p.passes_gates ? 'row-pass' : 'row-fail', style: 'cursor:pointer;' });
    tr.setAttribute('data-id', p.id);

    // Rank
    var tdRank = createEl('td', { style: 'font-weight:600;color:var(--text-muted);' }, String(p.rank));
    tr.appendChild(tdRank);

    // Title
    var tdTitle = createEl('td', { style: 'font-weight:500;max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;', title: p.short_title }, p.short_title);
    tr.appendChild(tdTitle);

    // Year
    tr.appendChild(createEl('td', {}, String(p.year)));

    // ND sparkbar
    var tdNd = createEl('td');
    var ndBar = createEl('span', { className: 'sparkbar sparkbar-nd', style: 'width:' + (p.nd * 0.6) + 'px' });
    var ndVal = createEl('span', { style: 'font-size:0.75rem;color:var(--nd-color);margin-left:4px;' }, String(p.nd));
    tdNd.appendChild(ndBar);
    tdNd.appendChild(ndVal);
    tr.appendChild(tdNd);

    // PE sparkbar
    var tdPe = createEl('td');
    var peBar = createEl('span', { className: 'sparkbar sparkbar-pe', style: 'width:' + (p.pe * 0.6) + 'px' });
    var peVal = createEl('span', { style: 'font-size:0.75rem;color:var(--pe-color);margin-left:4px;' }, String(p.pe));
    tdPe.appendChild(peBar);
    tdPe.appendChild(peVal);
    tr.appendChild(tdPe);

    // CI sparkbar
    var tdCi = createEl('td');
    var ciBar = createEl('span', { className: 'sparkbar sparkbar-ci', style: 'width:' + (p.ci * 0.6) + 'px' });
    var ciVal = createEl('span', { style: 'font-size:0.75rem;color:var(--ci-color);margin-left:4px;' }, String(p.ci));
    tdCi.appendChild(ciBar);
    tdCi.appendChild(ciVal);
    tr.appendChild(tdCi);

    // Composite
    tr.appendChild(createEl('td', { style: 'font-weight:700;font-family:var(--font-mono);' }, String(p.composite)));

    // Gate badge
    var tdGate = createEl('td');
    var gateBadge = createEl('span', { className: p.passes_gates ? 'gate-badge pass' : 'gate-badge fail' }, p.passes_gates ? 'PASS' : 'FAIL');
    tdGate.appendChild(gateBadge);
    tr.appendChild(tdGate);

    // Tradition dots
    var tdTrad = createEl('td');
    var tradClasses = ['virtue', 'deontological', 'utilitarian', 'care', 'contractarian'];
    p.traditions.forEach(function(t, i) {
      var dot = createEl('span', {
        className: t.active ? 'tradition-dot active-' + tradClasses[i] : 'tradition-dot',
        title: t.name + ': ' + t.score
      });
      tdTrad.appendChild(dot);
    });
    tr.appendChild(tdTrad);

    // Size
    var sizeStr = p.size >= 1000 ? (p.size / 1000).toFixed(0) + 'K' : String(p.size);
    tr.appendChild(createEl('td', { style: 'font-family:var(--font-mono);font-size:0.75rem;' }, sizeStr));

    // Format
    tr.appendChild(createEl('td', { style: 'font-size:0.75rem;' }, p.format));

    // A6
    tr.appendChild(createEl('td', { style: 'font-family:var(--font-mono);' }, String(p.a6)));

    tbody.appendChild(tr);

    // Expanded profile row (hidden)
    var expandTr = createEl('tr', { className: 'expanded-row', style: 'display:none;' });
    expandTr.setAttribute('data-expand', p.id);
    var expandTd = createEl('td', { colspan: '12' });
    expandTd.appendChild(buildProfileCard(p));
    expandTr.appendChild(expandTd);
    tbody.appendChild(expandTr);

    // Click handler
    tr.addEventListener('click', function() {
      expandTr.style.display = expandTr.style.display === 'none' ? 'table-row' : 'none';
    });
  });
}

function buildProfileCard(p) {
  var card = createEl('div', { className: 'profile-card' });

  // Normative Depth section
  var ndSection = createEl('div', { className: 'profile-section' });
  ndSection.appendChild(createEl('h4', {}, 'Normative Depth'));
  ndSection.appendChild(createEl('p', {}, 'Depth: ' + (p.depth || 'N/A')));
  ndSection.appendChild(createEl('p', {}, 'Reasoning: ' + (p.reasoning || 'N/A')));
  ndSection.appendChild(createEl('p', {}, 'Uncertainty: ' + (p.uncertainty || 'N/A')));
  ndSection.appendChild(createEl('p', {}, 'Pluralism: ' + (p.pluralism || 'N/A')));
  card.appendChild(ndSection);

  // Practical Ecosystem section
  var peSection = createEl('div', { className: 'profile-section' });
  peSection.appendChild(createEl('h4', {}, 'Practical Ecosystem'));
  peSection.appendChild(createEl('p', {}, 'Availability: ' + (p.availability || 'N/A')));
  peSection.appendChild(createEl('p', {}, 'License: ' + (p.license || 'N/A')));
  peSection.appendChild(createEl('p', {}, 'Implementability: ' + String(p.implementability)));
  peSection.appendChild(createEl('p', {}, 'Scorer: ' + (p.scorer_type || 'N/A')));
  card.appendChild(peSection);

  // Community Impact section
  var ciSection = createEl('div', { className: 'profile-section' });
  ciSection.appendChild(createEl('h4', {}, 'Community Impact'));
  ciSection.appendChild(createEl('p', {}, 'Citations: ' + String(p.citations)));
  ciSection.appendChild(createEl('p', {}, 'Venue: ' + (p.venue || 'N/A')));
  ciSection.appendChild(createEl('p', {}, 'Tier: ' + (p.venue_tier || 'N/A')));
  card.appendChild(ciSection);

  // Context section
  var ctxSection = createEl('div', { className: 'profile-section' });
  ctxSection.appendChild(createEl('h4', {}, 'Context'));
  ctxSection.appendChild(createEl('p', {}, 'Domain: ' + (p.domain || 'N/A')));
  ctxSection.appendChild(createEl('p', {}, 'Cultural: ' + (p.cultural || 'N/A')));
  var langStr = p.languages && p.languages.length > 0 ? p.languages.join(', ') : 'English only';
  ctxSection.appendChild(createEl('p', {}, 'Languages: ' + langStr));
  ctxSection.appendChild(createEl('p', {}, 'Annotators: ' + (p.annotators || 'N/A')));
  card.appendChild(ctxSection);

  // v2 Feature Highlights section
  var v2Section = createEl('div', { className: 'profile-section' });
  v2Section.appendChild(createEl('h4', {}, 'v2 Quality Metrics'));

  // E1 discriminative power (most important)
  var e1Str = p.e1_discriminative !== null && p.e1_discriminative !== undefined ? String(p.e1_discriminative) : 'N/A';
  var e1Color = 'var(--text-primary)';
  if (p.e1_discriminative !== null && p.e1_discriminative !== undefined) {
    e1Color = p.e1_discriminative >= 70 ? 'var(--accent-green)' : p.e1_discriminative >= 40 ? 'var(--accent-orange)' : 'var(--accent-red)';
  }
  var e1P = createEl('p');
  e1P.appendChild(document.createTextNode('E1 Discriminative: '));
  e1P.appendChild(createEl('span', { style: 'color:' + e1Color + ';font-weight:700;font-family:var(--font-mono);' }, e1Str));
  if (p.e1_rationale) {
    e1P.appendChild(createEl('span', { style: 'font-size:0.72rem;color:var(--text-muted);margin-left:6px;' }, '(' + p.e1_rationale.substring(0, 80) + ')'));
  }
  v2Section.appendChild(e1P);

  // B10 contamination
  var b10Str = p.b10_contamination !== null && p.b10_contamination !== undefined ? String(p.b10_contamination) : 'N/A';
  var b10Color = 'var(--text-primary)';
  if (p.b10_contamination !== null && p.b10_contamination !== undefined) {
    b10Color = p.b10_contamination >= 67 ? 'var(--accent-red)' : p.b10_contamination >= 33 ? 'var(--accent-orange)' : 'var(--accent-green)';
  }
  var b10P = createEl('p');
  b10P.appendChild(document.createTextNode('B10 Contamination: '));
  b10P.appendChild(createEl('span', { style: 'color:' + b10Color + ';font-weight:600;font-family:var(--font-mono);' }, b10Str));
  v2Section.appendChild(b10P);

  // A10 temporal depth
  v2Section.appendChild(createEl('p', {}, 'A10 Temporal: ' + (p.a10_temporal !== null && p.a10_temporal !== undefined ? String(p.a10_temporal) : 'N/A')));

  // A11 scenario realism
  v2Section.appendChild(createEl('p', {}, 'A11 Realism: ' + (p.a11_realism !== null && p.a11_realism !== undefined ? String(p.a11_realism) : 'N/A')));

  // Non-Western traditions
  var nwStr = p.nw_traditions && p.nw_traditions.length > 0 ? p.nw_traditions.join(', ') : 'None';
  v2Section.appendChild(createEl('p', {}, 'Non-Western: ' + nwStr));

  // Metaethical stance
  if (p.a9_metaethical) {
    v2Section.appendChild(createEl('p', {}, 'Metaethical: ' + p.a9_metaethical));
  }

  card.appendChild(v2Section);

  // Rationale
  if (p.rationale) {
    var ratDiv = createEl('div', { className: 'rationale-text' });
    ratDiv.appendChild(createEl('strong', {}, 'Rationale: '));
    ratDiv.appendChild(document.createTextNode(p.rationale));
    card.appendChild(ratDiv);
  }

  return card;
}

// ============================================================
// Search & Filter
// ============================================================
function setupSearch() {
  var searchInput = document.getElementById('paper-search');
  var gateFilter = document.getElementById('filter-gate');
  var tradFilter = document.getElementById('filter-tradition');
  var yearFilter = document.getElementById('filter-year');

  function applyFilters() {
    var q = searchInput.value.toLowerCase();
    var gate = gateFilter.value;
    var trad = tradFilter.value;
    var year = yearFilter.value;

    currentPapers = DATA_PAPERS_TABLE.filter(function(p) {
      if (q && p.short_title.toLowerCase().indexOf(q) === -1) return false;
      if (gate === 'pass' && !p.passes_gates) return false;
      if (gate === 'fail' && p.passes_gates) return false;
      if (year !== 'all' && String(p.year) !== year) return false;
      if (trad !== 'all') {
        var tradMap = { virtue: 0, deontological: 1, utilitarian: 2, care: 3, contractarian: 4 };
        var idx = tradMap[trad];
        if (idx !== undefined && !p.traditions[idx].active) return false;
      }
      return true;
    });

    // Re-rank
    currentPapers.forEach(function(p, i) { p.rank = i + 1; });
    renderPapersRows();
  }

  searchInput.addEventListener('input', applyFilters);
  gateFilter.addEventListener('change', applyFilters);
  tradFilter.addEventListener('change', applyFilters);
  yearFilter.addEventListener('change', applyFilters);
}

// ============================================================
// Sort
// ============================================================
function setupSort() {
  var headers = document.querySelectorAll('table.papers-table th[data-sort]');
  headers.forEach(function(th) {
    th.addEventListener('click', function() {
      var key = this.getAttribute('data-sort');
      if (currentSort.key === key) {
        currentSort.dir = currentSort.dir === 'asc' ? 'desc' : 'asc';
      } else {
        currentSort.key = key;
        currentSort.dir = key === 'short_title' || key === 'format' ? 'asc' : 'desc';
      }

      currentPapers.sort(function(a, b) {
        var va = a[key], vb = b[key];
        if (typeof va === 'string') va = va.toLowerCase();
        if (typeof vb === 'string') vb = vb.toLowerCase();
        if (typeof va === 'boolean') { va = va ? 1 : 0; vb = vb ? 1 : 0; }
        var cmp = va < vb ? -1 : va > vb ? 1 : 0;
        return currentSort.dir === 'asc' ? cmp : -cmp;
      });

      // Update ranks
      currentPapers.forEach(function(p, i) { p.rank = i + 1; });
      renderPapersRows();
    });
  });
}

// ============================================================
// Export CSV
// ============================================================
function setupExport() {
  document.getElementById('btn-export-csv').addEventListener('click', function() {
    var headers = ['Rank', 'Benchmark', 'Year', 'ND', 'PE', 'CI', 'Composite', 'Gate', 'Size', 'Format', 'A6'];
    var rows = currentPapers.map(function(p) {
      return [p.rank, '"' + p.short_title + '"', p.year, p.nd, p.pe, p.ci, p.composite,
              p.passes_gates ? 'PASS' : 'FAIL', p.size, p.format, p.a6].join(',');
    });
    var csv = headers.join(',') + '\n' + rows.join('\n');
    var blob = new Blob([csv], { type: 'text/csv' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'normeval-benchmarks.csv';
    a.click();
    URL.revokeObjectURL(url);
  });
}

// ============================================================
// Tab 6: Trials Table
// ============================================================
function renderTrialsTable() {
  var trials = DATA_TRIAL_DATA.trials;
  var tbody = document.getElementById('trials-tbody');
  tbody.textContent = '';

  trials.forEach(function(t) {
    var diffColor = t.framework_difficulty === 'Easy' ? 'var(--accent-green)' :
                    t.framework_difficulty === 'Hard' ? 'var(--accent-red)' : 'var(--accent-orange)';

    var tr = createEl('tr');
    tr.appendChild(createEl('td', { style: 'font-weight:600;' }, t.id));
    tr.appendChild(createEl('td', {}, t.name));
    tr.appendChild(createEl('td', { style: 'font-family:var(--font-mono);font-weight:600;' }, t.accuracy + '%'));
    tr.appendChild(createEl('td', { style: 'font-family:var(--font-mono);' }, String(t.items)));
    tr.appendChild(createEl('td', { style: 'color:' + diffColor + ';font-weight:500;' }, t.framework_difficulty));
    tr.appendChild(createEl('td', { style: 'font-family:var(--font-mono);' }, String(t.discriminative)));
    tr.appendChild(createEl('td', { style: 'font-family:var(--font-mono);' }, t.refusal_rate + '%'));
    tr.appendChild(createEl('td', { style: 'font-size:0.75rem;color:var(--text-secondary);' }, t.notes));
    tbody.appendChild(tr);
  });

  // Summary stats
  var sumContainer = document.getElementById('trial-summary-stats');
  sumContainer.textContent = '';
  var wrap = createEl('div', { style: 'padding:0.5rem;' });

  var p1 = createEl('p', { style: 'font-size:0.85rem;margin-bottom:0.4rem;' });
  p1.appendChild(createEl('strong', {}, 'Avg Accuracy: '));
  p1.appendChild(createEl('span', { style: 'color:var(--accent-green);font-weight:700;' }, DATA_TRIAL_DATA.avg_accuracy + '%'));
  wrap.appendChild(p1);

  var p2 = createEl('p', { style: 'font-size:0.85rem;margin-bottom:0.4rem;' });
  p2.appendChild(createEl('strong', {}, 'Avg Discriminative: '));
  p2.appendChild(createEl('span', { style: 'color:var(--accent-blue);font-weight:700;' }, String(DATA_TRIAL_DATA.avg_discriminative)));
  wrap.appendChild(p2);

  wrap.appendChild(createEl('p', { style: 'font-size:0.85rem;' }, 'Trials: ' + trials.length));
  sumContainer.appendChild(wrap);
}

// ============================================================
// Tab 8: Cross-Model Comparison
// ============================================================
function renderCrossModelTab() {
  var cm = DATA_CROSS_MODEL;
  if (cm.status !== 'complete') return;

  // KPI cards
  var kpiContainer = document.getElementById('cm-kpi-cards');
  if (!kpiContainer) return;
  kpiContainer.textContent = '';
  var kpis = [
    { value: String(cm.trials_completed), label: 'Trials Replicated', color: 'green' },
    { value: String(cm.total_items), label: 'Items Compared', color: 'blue' },
    { value: String(cm.models.length), label: 'Model Tiers', color: 'purple' },
    { value: cm.agreement_matrix.all_three.agreement_percent + '%', label: 'Three-Way Agreement', color: 'cyan' },
  ];
  kpis.forEach(function(k) {
    var col = createEl('div', { className: 'col-6 col-md-3' });
    var card = createEl('div', { className: 'metric-card' });
    card.appendChild(createEl('div', { className: 'metric-value ' + k.color }, k.value));
    card.appendChild(createEl('div', { className: 'metric-label' }, k.label));
    col.appendChild(card);
    kpiContainer.appendChild(col);
  });

  // Findings cards
  var findingsContainer = document.getElementById('cm-findings-list');
  if (findingsContainer && cm.findings) {
    findingsContainer.textContent = '';
    cm.findings.forEach(function(f) {
      var card = createEl('div', { className: 'claim-card', style: 'margin-bottom:0.75rem;' });
      var header = createEl('div', { style: 'display:flex;justify-content:space-between;align-items:center;margin-bottom:0.4rem;' });
      header.appendChild(createEl('strong', { style: 'font-size:0.85rem;' }, f.id + ': ' + f.title));
      card.appendChild(header);
      card.appendChild(createEl('p', { style: 'font-size:0.8rem;color:var(--text-secondary);margin-bottom:0.3rem;' }, f.evidence));
      card.appendChild(createEl('p', { style: 'font-size:0.78rem;color:var(--text-muted);' }, f.interpretation));
      findingsContainer.appendChild(card);
    });
  }

  // Agreement matrix table
  var agContainer = document.getElementById('cm-agreement-table');
  if (agContainer && cm.agreement_matrix) {
    agContainer.textContent = '';
    var am = cm.agreement_matrix;
    var tbl = createEl('table', { className: 'papers-table', style: 'font-size:0.82rem;' });
    var thead = createEl('thead');
    var htr = createEl('tr');
    ['Pair', 'Agreement'].forEach(function(h) { htr.appendChild(createEl('th', {}, h)); });
    thead.appendChild(htr);
    tbl.appendChild(thead);
    var tbody = createEl('tbody');
    [
      ['Opus \u2194 Sonnet', am.opus_sonnet.agreement_percent + '%'],
      ['Sonnet \u2194 Haiku', am.sonnet_haiku.agreement_percent + '%'],
      ['Opus \u2194 Haiku', am.opus_haiku.agreement_percent + '%'],
      ['All Three', am.all_three.agreement_percent + '%'],
    ].forEach(function(row) {
      var tr = createEl('tr');
      tr.appendChild(createEl('td', { style: 'font-weight:500;' }, row[0]));
      var color = parseFloat(row[1]) >= 80 ? 'var(--accent-green)' : parseFloat(row[1]) >= 70 ? 'var(--accent-orange)' : 'var(--accent-red)';
      tr.appendChild(createEl('td', { style: 'font-family:var(--font-mono);font-weight:700;color:' + color + ';' }, row[1]));
      tbody.appendChild(tr);
    });
    tbl.appendChild(tbody);
    agContainer.appendChild(tbl);
  }

  // Per-trial summary table
  var ptContainer = document.getElementById('cm-per-trial-table');
  if (ptContainer && cm.per_trial) {
    ptContainer.textContent = '';
    var tbl = createEl('table', { className: 'papers-table', style: 'font-size:0.78rem;' });
    var thead = createEl('thead');
    var htr = createEl('tr');
    ['Trial', 'Benchmark', 'Items', 'Finding'].forEach(function(h) { htr.appendChild(createEl('th', {}, h)); });
    thead.appendChild(htr);
    tbl.appendChild(thead);
    var tbody = createEl('tbody');
    Object.keys(cm.per_trial).forEach(function(key) {
      var t = cm.per_trial[key];
      var tr = createEl('tr');
      tr.appendChild(createEl('td', { style: 'font-weight:600;' }, key));
      tr.appendChild(createEl('td', {}, t.benchmark));
      tr.appendChild(createEl('td', { style: 'font-family:var(--font-mono);' }, String(t.items)));
      tr.appendChild(createEl('td', { style: 'font-size:0.72rem;color:var(--text-secondary);' }, t.finding));
      tbody.appendChild(tr);
    });
    tbl.appendChild(tbody);
    ptContainer.appendChild(tbl);
  }
}

// ============================================================
// Tab 10: Cross-Vendor Comparison
// ============================================================
function renderCrossVendorTab() {
  var cv = DATA_CROSS_VENDOR;
  if (!cv) return;

  // KPI cards
  var kpiContainer = document.getElementById('cv-kpi-cards');
  if (!kpiContainer) return;
  kpiContainer.textContent = '';
  var kpis = [
    { value: '9', label: 'Models (3 Vendors)', color: 'purple' },
    { value: '3', label: 'Effective Profiles', color: 'cyan' },
    { value: '90.4%', label: 'Top Cross-Vendor', color: 'green' },
    { value: '71.1%', label: 'Max Divergence', color: 'orange' },
  ];
  kpis.forEach(function(k) {
    var col = createEl('div', { className: 'col-6 col-md-3' });
    var card = createEl('div', { className: 'metric-card' });
    card.appendChild(createEl('div', { className: 'metric-value ' + k.color }, k.value));
    card.appendChild(createEl('div', { className: 'metric-label' }, k.label));
    col.appendChild(card);
    kpiContainer.appendChild(col);
  });

  // Findings cards (expandable on click)
  var findingsContainer = document.getElementById('cv-findings-list');
  if (findingsContainer && cv.findings) {
    findingsContainer.textContent = '';
    var toggleLink = createEl('div', { style: 'text-align:right;margin-bottom:0.5rem;' });
    var toggleBtn = createEl('a', { href: '#', style: 'font-size:0.75rem;color:var(--accent-blue);text-decoration:none;' }, 'Expand All');
    toggleBtn.addEventListener('click', function(e) {
      e.preventDefault();
      var details = findingsContainer.querySelectorAll('.finding-detail');
      var chevrons = findingsContainer.querySelectorAll('.finding-chevron');
      var allOpen = Array.from(details).every(function(d) { return d.style.display !== 'none'; });
      details.forEach(function(d) { d.style.display = allOpen ? 'none' : 'block'; });
      chevrons.forEach(function(c) { c.style.transform = allOpen ? 'rotate(0deg)' : 'rotate(90deg)'; });
      toggleBtn.textContent = allOpen ? 'Expand All' : 'Collapse All';
    });
    toggleLink.appendChild(toggleBtn);
    findingsContainer.appendChild(toggleLink);
    cv.findings.forEach(function(f) {
      var card = createEl('div', { className: 'claim-card', style: 'margin-bottom:0.75rem;cursor:pointer;transition:background 0.15s, border-color 0.2s;' });
      var header = createEl('div', { style: 'display:flex;justify-content:space-between;align-items:center;margin-bottom:0.4rem;' });
      var titleWrap = createEl('div', { style: 'display:flex;align-items:center;gap:0.4rem;' });
      var chevron = createEl('span', { className: 'finding-chevron', style: 'font-size:0.85rem;color:var(--text-secondary);transition:transform 0.2s;display:inline-block;' }, '\u25B6');
      titleWrap.appendChild(chevron);
      titleWrap.appendChild(createEl('strong', { style: 'font-size:0.85rem;' }, f.id + ': ' + f.title));
      header.appendChild(titleWrap);
      var badge = createEl('span', { className: 'gate-badge', style: 'font-size:0.65rem;padding:0.15rem 0.5rem;background:var(--accent-purple);color:#fff;border-radius:3px;' }, f.badge);
      header.appendChild(badge);
      card.appendChild(header);
      card.appendChild(createEl('p', { style: 'font-size:0.8rem;color:var(--text-secondary);margin-bottom:0;' }, f.subtitle));
      if (f.detail) {
        var detailEl = createEl('div', { className: 'finding-detail', style: 'font-size:0.78rem;color:var(--text-secondary);line-height:1.5;margin-top:0.6rem;padding-top:0.6rem;border-top:1px solid var(--border);display:none;' }, f.detail);
        card.appendChild(detailEl);
        card.addEventListener('click', function() {
          var isOpen = detailEl.style.display !== 'none';
          detailEl.style.display = isOpen ? 'none' : 'block';
          chevron.style.transform = isOpen ? 'rotate(0deg)' : 'rotate(90deg)';
          card.style.borderColor = isOpen ? '' : 'var(--accent-purple)';
        });
      }
      card.addEventListener('mouseenter', function() { card.style.background = 'var(--bg-hover)'; });
      card.addEventListener('mouseleave', function() { card.style.background = ''; });
      findingsContainer.appendChild(card);
    });
  }

  // Per-trial comparison table
  var ptContainer = document.getElementById('cv-per-trial-table');
  if (ptContainer && cv.per_trial) {
    ptContainer.textContent = '';
    var tbl = createEl('table', { className: 'papers-table', style: 'font-size:0.75rem;' });
    var thead = createEl('thead');
    var htr = createEl('tr');
    var trialMetrics = {
      'T6': 'MCQ Acc. (%)', 'T7': 'Change Rate (%)', 'T8': 'Abductive (1-3)',
      'T9': 'Accuracy (%)', 'T10': 'Consensus (0-5)', 'T11': 'MCQ Acc. (%)',
      'T12': 'Kohlberg Stage', 'T13': 'IH Mean (1-7)', 'T14': 'CBR Rate (%)',
      'T15': 'Accuracy (%)'
    };
    var headers = ['Trial', 'Benchmark', 'Metric'];
    var modelKeys = Object.keys(cv.per_trial.data[cv.per_trial.trials[0]]);
    modelKeys.forEach(function(m) { headers.push(m); });
    headers.forEach(function(h) { htr.appendChild(createEl('th', { style: 'white-space:nowrap;' }, h)); });
    thead.appendChild(htr);
    tbl.appendChild(thead);
    var tbody = createEl('tbody');
    cv.per_trial.trials.forEach(function(tid, i) {
      var tr = createEl('tr');
      tr.appendChild(createEl('td', { style: 'font-weight:600;' }, tid));
      tr.appendChild(createEl('td', {}, cv.per_trial.trial_names[i]));
      tr.appendChild(createEl('td', { style: 'font-size:0.7rem;color:var(--text-muted);white-space:nowrap;' }, trialMetrics[tid] || ''));
      var row = cv.per_trial.data[tid];
      modelKeys.forEach(function(m) {
        var val = row[m];
        var valStr = val !== undefined && val !== null ? String(val) : '-';
        var color = 'var(--text-primary)';
        if (typeof val === 'number') {
          if (val >= 100) color = 'var(--accent-green)';
          else if (val >= 50) color = 'var(--accent-blue)';
          else if (val >= 5) color = 'var(--accent-orange)';
        }
        tr.appendChild(createEl('td', { style: 'font-family:var(--font-mono);color:' + color + ';text-align:center;' }, valStr));
      });
      tbody.appendChild(tr);
    });
    tbl.appendChild(tbody);
    ptContainer.appendChild(tbl);
  }
}

// ============================================================
// Tab 9: Gaps
// ============================================================
function renderGapsTab() {
  var gaps = DATA_GAPS;

  // Peer review concerns
  var prContainer = document.getElementById('peer-review-list');
  prContainer.textContent = '';
  var statusColors = { resolved: '#4ecb71', mitigated: '#f0983e', acknowledged: '#9498b3', pending: '#ef5b5b' };
  var statusCounts = {};
  gaps.peer_review_concerns.forEach(function(c) {
    statusCounts[c.status] = (statusCounts[c.status] || 0) + 1;
    var borderColor = statusColors[c.status] || '#9498b3';
    var card = createEl('div', { className: 'claim-card', style: 'padding:0.75rem;border-left:3px solid ' + borderColor + ';' });
    var header = createEl('div', { style: 'display:flex;justify-content:space-between;align-items:center;' });
    header.appendChild(createEl('span', { style: 'font-size:0.82rem;' }, c.concern));
    var badge = createEl('span', { className: 'severity-badge ' + c.severity, style: 'background:' + borderColor + '22;color:' + borderColor + ';border:1px solid ' + borderColor + '44;' });
    badge.textContent = c.status;
    header.appendChild(badge);
    card.appendChild(header);
    if (c.resolution) {
      card.appendChild(createEl('div', { style: 'font-size:0.75rem;color:var(--text-secondary);margin-top:0.4rem;line-height:1.4;' }, c.resolution));
    }
    prContainer.appendChild(card);
  });
  // Progress summary
  var summaryParts = [];
  if (statusCounts.resolved) summaryParts.push(statusCounts.resolved + ' resolved');
  if (statusCounts.mitigated) summaryParts.push(statusCounts.mitigated + ' mitigated');
  if (statusCounts.acknowledged) summaryParts.push(statusCounts.acknowledged + ' acknowledged');
  if (statusCounts.pending) summaryParts.push(statusCounts.pending + ' pending');
  var summaryEl = createEl('div', { style: 'font-size:0.72rem;color:var(--text-muted);margin-top:0.5rem;text-align:center;' },
    summaryParts.join(' \u2022 ') + ' \u2014 ' + gaps.peer_review_concerns.length + ' total');
  prContainer.appendChild(summaryEl);

  // Care ethics prototype
  var careContainer = document.getElementById('care-prototype-card');
  if (careContainer && gaps.care_prototype) {
    careContainer.textContent = '';
    var cp = gaps.care_prototype;

    var cpWrap = createEl('div', { style: 'display:grid;grid-template-columns:1fr 1fr;gap:1rem;' });

    // Left: key insight + overall score
    var cpLeft = createEl('div');
    var insightCard = createEl('div', { className: 'claim-card', style: 'border-left:3px solid var(--accent-red);' });
    insightCard.appendChild(createEl('p', { style: 'font-size:0.85rem;font-weight:600;color:var(--accent-red);margin-bottom:0.5rem;' }, 'Key Insight'));
    insightCard.appendChild(createEl('p', { style: 'font-size:0.82rem;color:var(--text-primary);margin-bottom:0.5rem;' }, cp.key_insight));
    insightCard.appendChild(createEl('p', { style: 'font-size:0.78rem;color:var(--text-secondary);' }, cp.competence_finding));
    cpLeft.appendChild(insightCard);

    var metaCard = createEl('div', { className: 'claim-card', style: 'margin-top:0.75rem;' });
    metaCard.appendChild(createEl('p', { style: 'font-size:0.82rem;' }, 'Format: ' + cp.format));
    metaCard.appendChild(createEl('p', { style: 'font-size:0.82rem;' }, 'Scenarios: ' + cp.scenarios + ' (' + cp.categories.join(', ') + ')'));
    metaCard.appendChild(createEl('p', { style: 'font-size:0.82rem;' }, 'Overall: ' + cp.overall_score));
    cpLeft.appendChild(metaCard);
    cpWrap.appendChild(cpLeft);

    // Right: dimension bars
    var cpRight = createEl('div');
    var dimCard = createEl('div', { className: 'claim-card' });
    dimCard.appendChild(createEl('p', { style: 'font-size:0.82rem;font-weight:600;margin-bottom:0.75rem;' }, 'Tronto Dimensions (0-4 scale)'));

    cp.dimensions.forEach(function(dim) {
      var row = createEl('div', { style: 'display:flex;align-items:center;margin-bottom:0.5rem;' });
      row.appendChild(createEl('span', { style: 'width:110px;font-size:0.78rem;color:var(--text-secondary);' }, dim.name));

      var barOuter = createEl('div', { style: 'flex:1;height:18px;background:var(--bg-primary);border-radius:4px;overflow:hidden;margin:0 0.5rem;' });
      var barColor = dim.pct >= 95 ? 'var(--accent-green)' : dim.pct >= 90 ? 'var(--accent-blue)' : 'var(--accent-orange)';
      var barInner = createEl('div', { style: 'width:' + dim.pct + '%;height:100%;background:' + barColor + ';border-radius:4px;transition:width 0.5s;' });
      barOuter.appendChild(barInner);
      row.appendChild(barOuter);

      row.appendChild(createEl('span', { style: 'width:50px;font-size:0.78rem;font-family:var(--font-mono);font-weight:600;color:' + barColor + ';' }, dim.pct + '%'));
      dimCard.appendChild(row);
    });

    cpRight.appendChild(dimCard);
    cpWrap.appendChild(cpRight);
    careContainer.appendChild(cpWrap);
  }

  // Mining candidates
  var mContainer = document.getElementById('mining-list');
  mContainer.textContent = '';
  var mScroll = createEl('div', { style: 'max-height:350px;overflow-y:auto;' });
  gaps.vault_mining.candidates.forEach(function(c) {
    var item = createEl('div', { style: 'padding:0.4rem 0;border-bottom:1px solid var(--border-color);font-size:0.8rem;' });
    var fname = c.filename.replace(/\.md$/, '').replace(/^\d{4}-/, '');
    item.appendChild(createEl('strong', { style: 'color:var(--accent-green);' }, fname.substring(0, 50)));
    item.appendChild(createEl('p', { style: 'color:var(--text-muted);font-size:0.72rem;margin:0.2rem 0 0;' }, c.reason.substring(0, 120) + '...'));
    mScroll.appendChild(item);
  });
  mContainer.appendChild(mScroll);
  mContainer.appendChild(createEl('p', { style: 'font-size:0.75rem;color:var(--text-muted);margin-top:0.5rem;' },
    'Total candidates: ' + gaps.vault_mining.total + ' | Include: ' + gaps.vault_mining.include + ' | Review: ' + gaps.vault_mining.review));

  // External search
  var eContainer = document.getElementById('external-list');
  eContainer.textContent = '';
  var eScroll = createEl('div', { style: 'max-height:350px;overflow-y:auto;' });
  gaps.external_search.candidates.forEach(function(c) {
    var item = createEl('div', { style: 'padding:0.5rem 0;border-bottom:1px solid var(--border-color);font-size:0.8rem;' });
    var titleLine = createEl('div');
    titleLine.appendChild(createEl('strong', {}, c.title.substring(0, 60)));
    titleLine.appendChild(createEl('span', { style: 'color:var(--text-muted);font-size:0.72rem;' }, ' (' + c.year + ', ' + c.source + ')'));
    item.appendChild(titleLine);
    item.appendChild(createEl('p', { style: 'color:var(--text-muted);font-size:0.72rem;margin:0.2rem 0 0;' }, c.reason.substring(0, 150)));
    eScroll.appendChild(item);
  });
  eContainer.appendChild(eScroll);
  eContainer.appendChild(createEl('p', { style: 'font-size:0.75rem;color:var(--text-muted);margin-top:0.5rem;' },
    'Total external: ' + gaps.external_search.total + ' | Add: ' + gaps.external_search.add + ' | Monitor: ' + gaps.external_search.monitor));
}
